### PR TITLE
- Initial version of AeronProcessor functionality

### PR DESCRIPTION
**Pull request by kadyana**

### CODE REVIEW

**Comment by jbrisbin** [comment]
This is a fantastic PR @kadyana ! Hopefully @smaldini Will have same time this week to review.

**Comment by kadyana** [comment]
Thank you :)

**Comment by ifesdjeen** [comment]
I'm currently working on Kafka :) (also, mesos, but that will most likely be not exactly a Processor)

**Comment by smaldini** [comment]
If awesomeness had github login alias it would be @ifesdjeen and @kadyana !

**Comment by ifesdjeen** [comment]
It would be quite useful to separate `Publisher` and `Subscriber` and (maybe) provide a `Processor` as a simple proxy (actually, exactly as it is implemented right now).

I suggest to make those internal calsses effectively public and allow splitting Subscriber and Publisher. 

If you think of use-cases, it's more often that you read from one channel (or queue, fwiw) and publish to the other one.

**Comment by kadyana** [comment]
@ifesdjeen I agree with you. As discussed with @smaldini we do the initial implementation which is going to be improved in the next iteration. This is the initial version. The update to this PR will move things closer to the separation you mentioned.

**Comment by ifesdjeen** [comment]
@kadyana perfect!

**Comment by kadyana** [comment]
Closed as a new one on a new branch is about to be created.

**Pull request closed without merging**
