### PR TITLE
Remove redundant code, simplification and mild optimisation

### PR DESCRIPTION
**Pull request by sirinath**
Replaced some items with vargs

[Review on Reviewable](https://reviewable.io/reviews/reactor/reactor/537)

### CODE REVIEW

**Comment by smaldini** [comment]
Mhh doesn't this prevent things like Streams.concat(IntegerStream, LongStream);

**Comment by sirinath** [comment]
No it does not

**Comment by sirinath** [comment]
Look it this is OK

**Comment by smaldini** [comment]
Changing internals will need a new review I'm afraid, closing for now but be sure that we heavily benchmark our critical paths and compare to the market now :)

**Pull request closed without merging**
