### PR TITLE
Add Pair class

### PR DESCRIPTION
**Pull request by ifesdjeen**
Pair class would be a good addition to currently existing Tuple. 

Thing with tuple is that it's an array lookup and it's constructed from the array and works with the raw types.

For tight integration with systems like Kafka (or anything that can serve as a Publisher of Pairs), it's necessary to have a possiblity of directly creating (without creating a wrapper array) a Pair.

### CODE REVIEW

**Comment by smaldini** [comment]
Tuple2 is a Pair basically:

private static final long serialVersionUID = -565933838909569191L;

	public final T2 t2;

	Tuple2(int size, T1 t1, T2 t2) {
		super(size, t1);
		this.t2 = t2;

**Comment by smaldini** [comment]
We can rename it tho

**Comment by ifesdjeen** [comment]
I'm currently using Tuple2 instead of Pair (so far uncommited code). 

The only problem is that Tuple2 can only be created by creating a wrapper array. I thought that adding a Pair as an integration endpoint could be useful and a bit more performant.

So that's mostly for performance reasons.

**Comment by smaldini** [comment]
But you got Tuple.from(T1, T2) which does new Tuple2(size, t1,t2)

**Comment by smaldini** [comment]
there's size however which is not used.

**Comment by ifesdjeen** [comment]
Ah, looked up the code. Ok, all cool :)

**Comment by smaldini** [comment]
When I did that change for 2.0 I thought about you actually :D And the point reduce operations might have been GC wore.

**Comment by ifesdjeen** [comment]
:) hehe

**Comment by ifesdjeen** [comment]
I should have been reading the code more carefully :)

**Pull request closed without merging**
