### PR TITLE
Add reactor-kafka-tools

### PR DESCRIPTION
**Pull request by kdombeck**
Add [reactor-kafka-tools](https://github.com/reactor/reactor-kafka) similar as to the way ```reactor-tools``` was added.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kdombeck Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor&pullRequestId=688)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor&pullRequestId=688) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kdombeck Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor&pullRequestId=688)!

**Comment by simonbasle** [comment]
@bsideup having a look at `reactor-kafka-tools`, it feels under-documented (no README for instance) and unclear whether or not this should be part of the BOM. what is your advice on the matter?

**Comment by bsideup** [comment]
`reactor-kafka-tools` is an "internal" module and ideally should not even be published. Ideally, we should consider deprecating it (the published module) and removing in the next major release of r-kafka.

**Pull request closed without merging**
