### PR TITLE
Bismuth

### PR DESCRIPTION
**Pull request by RupendraKota**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@RupendraKota Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor&pullRequestId=649)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor&pullRequestId=649) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@RupendraKota Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor&pullRequestId=649)!

**Comment by simonbasle** [comment]
What is this PR? What were you trying to achieve @RupendraKota ?
`Bismuth` is the maintenance branch of the previous release train. `master` is the branch for the currently under development release train (`Californium`).

**Comment by RupendraKota** [comment]
Hi apologies,

Just created a pull request and sync caused that.

Thanks,
RK

**Pull request closed without merging**
